version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'
    assignees:
      - 'y-hsgw'
    groups:
      react-stack:
        patterns:
          - react
          - react-dom
          - '@types/react'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'docker'
    ignore:
      - dependency-name: '*'
      - update-types:
          - version-update:semver-major

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ga'
